system_configuration:
    groups:
        alert_additional_settings_segment:
            title: 'aligent.announcement.alert_block.group.title'

    fields:
        aligent_announcement.alert_block_background_colour:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\ColorType'
            options:
                label: 'aligent.announcement.alert_block.colour.label'
                tooltip: 'aligent.announcement.alert_block.colour.hint'
        aligent_announcement.alert_block_date_start:
            data_type: string
            type: 'Oro\Bundle\FormBundle\Form\Type\OroDateType'
            options:
                label: 'aligent.announcement.alert_block.date_start.label'
                tooltip: 'aligent.announcement.alert_block.date_start.hint'
        aligent_announcement.alert_block_date_end:
            data_type: string
            type: 'Oro\Bundle\FormBundle\Form\Type\OroDateType'
            options:
                label: 'aligent.announcement.alert_block.date_end.label'
                tooltip: 'aligent.announcement.alert_block.date_end.hint'
        aligent_announcement.alert_block_alias:
            data_type: string
            type: 'Aligent\AnnouncementBundle\Form\Type\ContentBlockSelectType'
            options:
                label: 'aligent.announcement.alert_block.block_alias.label'
                tooltip: 'aligent.announcement.alert_block.block_alias.hint'

    tree:
        system_configuration:
            commerce:
                children:
                    marketing:
                        children:
                            alert_additional_settings_segment:
                                priority: 0
                                children:
                                    alert_additional_settings_segment:
                                        children:
                                            - aligent_announcement.alert_block_background_colour
                                            - aligent_announcement.alert_block_date_start
                                            - aligent_announcement.alert_block_date_end
                                            - aligent_announcement.alert_block_alias
        website_configuration:
            commerce:
                children:
                    marketing:
                        children:
                            alert_additional_settings_segment:
                                priority: 0
                                children:
                                    alert_additional_settings_segment:
                                        children:
                                            - aligent_announcement.alert_block_background_colour
                                            - aligent_announcement.alert_block_date_start
                                            - aligent_announcement.alert_block_date_end
                                            - aligent_announcement.alert_block_alias
