parameters:
    # Form Type
    alg_alert.form.content_block_select_type.class: Aligent\AnnouncementBundle\Form\Type\ContentBlockSelectType

services:
    # Form Types
    Aligent\AnnouncementBundle\Form\Type\ContentBlockSelectType:
        arguments:
            - '@doctrine'
        tags:
            - { name: form.type, alias: alg_content_block_select }

    # Layout DataProviders
    Aligent\AnnouncementBundle\Layout\DataProvider\AnnouncementDataProvider:
        arguments:
            - '@oro_config.manager'
            - '@oro_website.manager'
            - '@oro_locale.settings'
        tags:
            - { name: layout.data_provider, alias: alert_content_block }
